
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#check what this do :
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

spring.kafka.consumer.auto-offset-reset=earliest
