spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.auto-offset-reset=earliest

# =========================
# IMPORTANT FOR KONG
# =========================
server.forward-headers-strategy=framework
server.use-forward-headers=true

# =========================
# SPRINGDOC
# =========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

springdoc.swagger-ui.use-root-path=false
springdoc.swagger-ui.disable-swagger-default-url=true