<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_product_list' => [[], ['_controller' => 'App\\Controller\\ProductController::list'], [], [['text', '/api/store/products/']], [], [], []],
    'app_product_search' => [[], ['_controller' => 'App\\Controller\\ProductController::search'], [], [['text', '/api/store/products/search']], [], [], []],
    'app_product_show' => [['productId'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/api/store/products']], [], [], []],
    'App\Controller\ProductController::list' => [[], ['_controller' => 'App\\Controller\\ProductController::list'], [], [['text', '/api/store/products/']], [], [], []],
    'App\Controller\ProductController::search' => [[], ['_controller' => 'App\\Controller\\ProductController::search'], [], [['text', '/api/store/products/search']], [], [], []],
    'App\Controller\ProductController::show' => [['productId'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/api/store/products']], [], [], []],
];
