services:

  gym-user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym-user-service
    ports:
      - "5000:8080"
    environment:
      
      - ASPNETCORE_ENVIRONMENT=Development

      
      - ConnectionStrings__DefaultConnection=Host=gym-user-db;Port=5432;Database=user_service_db;Username=postgres;Password=${POSTGRES_PASSWORD}

      
      - BootstrapAdmin__Enabled=true
      - BootstrapAdmin__Email=admin@gym.com
      - BootstrapAdmin__Password=${BOOTSTRAP_ADMIN_PASSWORD}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
    depends_on:
      gym-user-db:
        condition: service_healthy
    networks:
      - gym-network
    volumes:
      - ./Keys:/app/Keys   

 

  gym-user-db:
    image: postgres:15
    container_name: gym-user-db
    restart: always
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    ports:
      - "5433:5432"
    volumes:
      - gym-user-db-data:/var/lib/postgresql/data
    networks:
      - gym-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  gym-network:
    driver: bridge

volumes:
  gym-user-db-data:
